[containers]
# enable user-space networking (worse performance compared to `netns="host"`, but allows port remapping)
netns="pasta"
userns="host"
ipcns="host"
utsns="host"
cgroupns="host"
cgroups="disabled"
log_driver = "k8s-file"

# Workaround against `crun` mount issues
default_sysctls=[]
volumes = ["/proc:/proc"]

[engine]
cgroup_manager = "cgroupfs"
events_logger="file"
runtime="crun"
